// <auto-generated />
using System;
using AccesoDatos.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDatos.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260321202917_MakeReunionCotizacionIdNullable")]
    partial class MakeReunionCotizacionIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogicaDeNegocio.Entidades.Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadInvitados")
                        .HasColumnType("int");

                    b.Property<int?>("EventoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrecioPorInvitado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cotizacion", (string)null);
                });

            modelBuilder.Entity("LogicaDeNegocio.Entidades.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadInvitados")
                        .HasColumnType("int");

                    b.Property<int?>("CotizacionId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoEvento")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkCompartible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PlanificacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioPorInvitado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CotizacionId")
                        .IsUnique()
                        .HasFilter("[CotizacionId] IS NOT NULL");

                    b.ToTable("Evento", (string)null);
                });

            modelBuilder.Entity("LogicaDeNegocio.Entidades.Planificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadMesas")
                        .HasColumnType("int");

                    b.Property<string>("ConfiguracionMesasJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraComida")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraLlegada")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraSalida")
                        .HasColumnType("time");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("EventoId")
                        .IsUnique();

                    b.ToTable("Planificacion", (string)null);
                });

            modelBuilder.Entity("LogicaDeNegocio.Entidades.Reunion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CotizacionId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CotizacionId");

                    b.ToTable("Reunion", (string)null);
                });

            modelBuilder.Entity("LogicaDeNegocio.Entidades.ServicioEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PlanificacionId")
                        .HasColumnType("int");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanificacionId");

                    b.ToTable("ServicioEvento", (string)null);
                });

            modelBuilder.Entity("LogicaDeNegocio.Entidades.TimingEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<string>("Momento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("PlanificacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanificacionId");

                    b.ToTable("TimingEvento", (string)null);
                });

            modelBuilder.Entity("LogicaDeNegocio.Entidades.Evento", b =>
                {
                    b.HasOne("LogicaDeNegocio.Entidades.Cotizacion", "Cotizacion")
                        .WithOne("Evento")
                        .HasForeignKey("LogicaDeNegocio.Entidades.Evento", "CotizacionId");

                    b.Navigation("Cotizacion");
                });

            modelBuilder.Entity("LogicaDeNegocio.Entidades.Planificacion", b =>
                {
                    b.HasOne("LogicaDeNegocio.Entidades.Evento", "Evento")
                        .WithOne("Planificacion")
                        .HasForeignKey("LogicaDeNegocio.Entidades.Planificacion", "EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("LogicaDeNegocio.Entidades.Reunion", b =>
                {
                    b.HasOne("LogicaDeNegocio.Entidades.Cotizacion", "Cotizacion")
                        .WithMany()
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cotizacion");
                });

            modelBuilder.Entity("LogicaDeNegocio.Entidades.ServicioEvento", b =>
                {
                    b.HasOne("LogicaDeNegocio.Entidades.Planificacion", "Planificacion")
                        .WithMany("ServicioEvento")
                        .HasForeignKey("PlanificacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planificacion");
                });

            modelBuilder.Entity("LogicaDeNegocio.Entidades.TimingEvento", b =>
                {
                    b.HasOne("LogicaDeNegocio.Entidades.Planificacion", "Planificacion")
                        .WithMany("TimingsEvento")
                        .HasForeignKey("PlanificacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planificacion");
                });

            modelBuilder.Entity("LogicaDeNegocio.Entidades.Cotizacion", b =>
                {
                    b.Navigation("Evento");
                });

            modelBuilder.Entity("LogicaDeNegocio.Entidades.Evento", b =>
                {
                    b.Navigation("Planificacion");
                });

            modelBuilder.Entity("LogicaDeNegocio.Entidades.Planificacion", b =>
                {
                    b.Navigation("ServicioEvento");

                    b.Navigation("TimingsEvento");
                });
#pragma warning restore 612, 618
        }
    }
}
